
{$O-,W+,V-,J+}

//version for DragonPlot


//{$WEAKLINKRTTI ON}
//{$RTTI EXPLICIT METHODS([]) PROPERTIES([]) FIELDS([])}


//options included
   {$Define Nevadia}
   {$Define Judomia}
   {$Define DragonPlot}
   {$Define UseMICRODEMDefaults}
   {$Define HideHelpButtons}
   {$Define RecordProblems}
   {$Define VCL}
   {$Define dBase_DefaultDBs}
   {$Define NoModeChanges}
   {$Define ExGDAL}
   {$Define ExPointCloud}
   {$Define ExLasLidar}
   {$Define ExSatStats}
   {$Define ExDBImages}
   {$Define ExFMX3D}
//{$Define ExAdvancedSats}
   {$Define ExMrSID}
   {$Define ExTerrainClassify}
   {$Define ExPOTRACE}
   {$Define ExPrincComp}
   {$Define ExMultiGrid}
   //{$Define ExSats}
   //{$Define ExNLCD}
   {$Define ExcludeExternalTools}
   {$Define NoExternalPrograms}
   {$Define ExTissot}
   //{$Define ExMICRONET}
   {$Define ExAutoOpen}
   {$Define ExOTB}
   {$Define ExSplash}
   {$Define ExRiverNetworks}
   {$Define ExDigitize}
   {$Define ExMGT}

   {$Define NoDBGrafs}
   {$Define NoDBGraphs}

   //{$Define ExRegisterView}


   {$Define UseTDBF}
   {$Define dBase_DefaultDBs}
   {$Define ExactRecordCountFix}
   //{$Define SQLiteDefaultDBs}
   {$Define UseTCLientDataSet}


    {$Define ExOpenGL}

//{$Define DragonPlotDemo}

{$IfDef DragonPlotDemo}
   {$Define ExTIGER}
   {$Define ExPLSS}
   //{$Define ExWeb}
{$EndIf}

{$Define ExOSM}
{$Define ExGeology}
{$Define NoSatelliteForms}
{$Define ExPointCloudMemory}


{$Define ExNaturalEarth}

{$Define ExMilIcons}
{$Define ExViewDEMHeader}
{$Define ExAdvanced3D}
{$Define ExVectorOverlay}
{$Define ExDTED}
{$Define ExOddballDEMexports}
{$Define ExStereoNet}
{$Define ExProjects}

{$Define ExAdvancedGIS}
{$Define ExAdvancedSats}
{$Define ExAdvancedImportExport}
{$Define ExAllSubframeImagery}
{$Define ExAlphaBlending}
{$Define exaltimeter}
{$Define ExAmbush}
{$Define ExAsterLag}
{$Define ExAVI}
{$Define ExAVI2GIF}
{$Define ExBlendMovie}
{$Define ExBlueMarble}
{$Define ExCartography}
{$Define ExCGM}
{$Define ExCGMDemo}
{$Define ExComplexGeostats}
{$Define ExComPort}
{$Define ExConvert}
{$Define ExDataManip}
{$Define ExDownloadData}
{$Define ExDrainage}
{$Define ExDriftModel}
{$Define ExExif}
{$Define ExExoticMaps}
{$Define ExFly}
{$Define ExFourier}
{$Define ExFresnel}
{$Define ExFTP}
{$Define ExGeography}
{$Define ExGeostats}
{$Define ExGeosym}
{$Define ExGMTGridding}
{$Define ExGPS}
{$Define ExGridComputing}
{$Define ExGridOverMap}
{$Define ExHyperSpectral}
{$Define ExImageClassify}
{$Define ExMakeLCGrid}
{$Define ExMilIcons}
{$Define ExModis}
{$Define ExMovies}
{$Define Exnet}
{$Define ExOblique}
{$Define ExOceanography}
{$Define ExOpenGL}
{$Define ExPClouder}
{$Define ExPocketPanorama}
{$Define ExRasterGIS}
{$Define ExRedistrict}
{$Define ExRegisterImage}
{$Define ExRGBThreeColors}
{$Define ExSatAdvanced}
{$Define ExSatImport}
{$Define exscanner}
{$Define ExSensorManager}
{$Define ExSidescan}
{$Define ExSlicer3D}
{$Define ExStereo}
{$Define ExTIN}
{$Define ExTCP}
{$Define ExTernary}
{$Define ExTextResultsWindow}
{$Define ExTINGraph}
{$Define ExTopoGrain}
{$Define ExTrackSat}
{$Define ExVariableOpaques}
{$Define ExVegGrid}
{$Define ExVegDensity}
{$Define ExWaveRerfraction}
{$Define ExZipatone}
{$Define NoClustering}